In [7]:
import pandas as pd
import numpy as np

In [8]:
companies = pd.read_excel("companies.xlsx")
balancesheet = pd.read_excel("balancesheet.xlsx")
cashflow = pd.read_excel("cashflow.xlsx")
profitandloss = pd.read_excel("profitandloss.xlsx")
analysis = pd.read_excel("analysis.xlsx")
prosandcons = pd.read_excel("prosandcons.xlsx")
documents = pd.read_excel("documents.xlsx")

In [9]:
companies.head()

,Mkt Fintech — Nifty 100 | Companies | 92 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7

In [10]:
def fix_headers(df):
    df.columns = df.iloc[0]   # Set first row as header
    df = df[1:]               # Remove first row
    df.reset_index(drop=True, inplace=True)
    return df

In [11]:
companies = fix_headers(companies)
balancesheet = fix_headers(balancesheet)
cashflow = fix_headers(cashflow)
profitandloss = fix_headers(profitandloss)
analysis = fix_headers(analysis)
prosandcons = fix_headers(prosandcons)
documents = fix_headers(documents)

In [12]:
companies.head()

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
0,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
1,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
2,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
3,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7
4,ADANIPORTS,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Ports & Special Economic Zone Ltd\n,https://in.tradingview.com/chart/?symbol=NSE%3...,Adani Ports & Special Economic Zone is in the ...,http://www.adaniports.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,2,265,12.9,18.1

In [13]:
balancesheet.head()

,id,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_asset,total_assets
0,136,ABB,Dec 2012,21,626,0,260,907,109,1,0,798,907
1,137,ABB,Mar 2014,21,767,0,351,1139,98,1,0,1040,1139
2,138,ABB,Mar 2015,21,916,0,436,1374,96,4,0,1274,1374
3,139,ABB,Mar 2016,21,1174,0,421,1616,108,3,0,1505,1616
4,140,ABB,Mar 2017,21,1366,0,679,2066,110,6,0,1950,2066

In [14]:
cashflow.head()

,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
0,37,TCS,Mar-13,11615,-6038,-5729,-152
1,38,TCS,Mar-14,14751,-9452,-5673,-374
2,39,TCS,Mar-15,19369,-1807,-17168,394
3,40,TCS,Mar-16,19109,-5010,-9666,4433
4,41,TCS,Mar-17,25223,-16895,-11026,-2698

In [15]:
profitandloss.head()

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
0,61,ABB,Dec 2012,1653,1451,202,12,33,0,19,215,33,145,68,25
1,62,ABB,Mar 2014,2276,2009,267,12,49,0,22,295,33,198,93,25
2,63,ABB,Mar 2015,2289,1977,312,14,48,0,15,344,34,229,108,29
3,64,ABB,Mar 2016,2614,2250,365,14,50,3,14,398,36,255,120,29
4,65,ABB,Mar 2017,2903,2505,398,14,57,2,16,436,37,277,130,31

In [16]:
profitandloss.tail()

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
1271,1370,INDIGO,Mar 2021,14641,2170,14638,2,0,1036,4699,-5830,0,-6171,-151,0
1272,1371,INDIGO,Mar 2022,25931,2386,25373,558,2,725,5068,-6171,0,-317,-160,0
1273,1372,INDIGO,Mar 2023,54446,3168,47926,6521,12,1431,5101,-317,0,-317,-8,0
1274,1373,INDIGO,Mar 2024,68904,4805,52573,16331,24,2326,6406,8043,-2,8167,212,0
1275,1374,INDIGO,TTM,76476,0,60568,15908,21,3034,7955,6182,NaN,6074,157,NaN

In [17]:
documents.head()

0 id company_id  Year                                      Annual_Report
0  1        ABB  2024  https://www.bseindia.com/xml-data/corpfiling/A...
1  2        ABB  2023  https://www.bseindia.com/xml-data/corpfiling/A...
2  3        ABB  2022  https://www.bseindia.com/bseplus/AnnualReport/...
3  4        ABB  2021  https://www.bseindia.com/bseplus/AnnualReport/...
4  5        ABB  2020  https://www.bseindia.com/bseplus/AnnualReport/...

In [18]:
profitandloss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1276 non-null   object
 1   company_id         1276 non-null   object
 2   year               1276 non-null   object
 3   sales              1276 non-null   object
 4   expenses           1276 non-null   object
 5   operating_profit   1263 non-null   object
 6   opm_percentage     1261 non-null   object
 7   other_income       1276 non-null   object
 8   interest           1276 non-null   object
 9   depreciation       1276 non-null   object
 10  profit_before_tax  1276 non-null   object
 11  tax_percentage     1181 non-null   object
 12  net_profit         1276 non-null   object
 13  eps                1271 non-null   object
 14  dividend_payout    1173 non-null   object
dtypes: object(15)
memory usage: 149.7+ KB

In [19]:
profit_columns = [
    'sales',
    'expenses',
    'operating_profit',
    'opm_percentage',
    'other_income',
    'interest',
    'depreciation',
    'profit_before_tax',
    'tax_percentage',
    'net_profit',
    'eps',
    'dividend_payout'
]

for col in profit_columns:
    profitandloss[col] = pd.to_numeric(
        profitandloss[col],
        errors='coerce'
    )

In [20]:
profitandloss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1276 non-null   object
 1   company_id         1276 non-null   object
 2   year               1276 non-null   object
 3   sales              1276 non-null   int64
 4   expenses           1276 non-null   int64
 5   operating_profit   1263 non-null   float64
 6   opm_percentage     1261 non-null   float64
 7   other_income       1276 non-null   int64
 8   interest           1276 non-null   int64
 9   depreciation       1276 non-null   int64
 10  profit_before_tax  1276 non-null   int64
 11  tax_percentage     1181 non-null   float64
 12  net_profit         1276 non-null   int64
 13  eps                1271 non-null   float64
 14  dividend_payout    1173 non-null   float64
dtypes: float64(5), int64(7), object(3)
memory usage: 149.7+ KB

In [21]:
balancesheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1312 entries, 0 to 1311
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1312 non-null   object
 1   company_id         1312 non-null   object
 2   year               1312 non-null   object
 3   equity_capital     1312 non-null   object
 4   reserves           1312 non-null   object
 5   borrowings         1312 non-null   object
 6   other_liabilities  1312 non-null   object
 7   total_liabilities  1312 non-null   object
 8   fixed_assets       1312 non-null   object
 9   cwip               1312 non-null   object
 10  investments        1312 non-null   object
 11  other_asset        1312 non-null   object
 12  total_assets       1312 non-null   object
dtypes: object(13)
memory usage: 133.4+ KB

In [22]:
balance_columns = [
    'equity_capital',
    'reserves',
    'borrowings',
    'other_liabilities',
    'total_liabilities',
    'fixed_assets',
    'cwip',
    'investments',
    'other_asset',
    'total_assets'
]

for col in balance_columns:
    balancesheet[col] = pd.to_numeric(
        balancesheet[col],
        errors='coerce'
    )

In [23]:
balancesheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1312 entries, 0 to 1311
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1312 non-null   object
 1   company_id         1312 non-null   object
 2   year               1312 non-null   object
 3   equity_capital     1312 non-null   float64
 4   reserves           1312 non-null   int64
 5   borrowings         1312 non-null   int64
 6   other_liabilities  1312 non-null   int64
 7   total_liabilities  1312 non-null   int64
 8   fixed_assets       1312 non-null   int64
 9   cwip               1312 non-null   int64
 10  investments        1312 non-null   int64
 11  other_asset        1312 non-null   int64
 12  total_assets       1312 non-null   int64
dtypes: float64(1), int64(9), object(3)
memory usage: 133.4+ KB

In [24]:
cashflow.columns

Index(['id', 'company_id', 'year', 'operating_activity', 'investing_activity',
       'financing_activity', 'net_cash_flow'],
      dtype='object', name=0)

In [25]:
cashflow.head()

,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
0,37,TCS,Mar-13,11615,-6038,-5729,-152
1,38,TCS,Mar-14,14751,-9452,-5673,-374
2,39,TCS,Mar-15,19369,-1807,-17168,394
3,40,TCS,Mar-16,19109,-5010,-9666,4433
4,41,TCS,Mar-17,25223,-16895,-11026,-2698

In [26]:
cashflow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187 entries, 0 to 1186
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  1187 non-null   object
 1   company_id          1187 non-null   object
 2   year                1187 non-null   object
 3   operating_activity  1185 non-null   object
 4   investing_activity  1185 non-null   object
 5   financing_activity  1185 non-null   object
 6   net_cash_flow       1185 non-null   object
dtypes: object(7)
memory usage: 65.0+ KB

In [27]:
cashflow_columns = [
    'operating_activity',
    'investing_activity',
    'financing_activity',
    'net_cash_flow'
]

for col in cashflow_columns:
    cashflow[col] = pd.to_numeric(
        cashflow[col],
        errors='coerce'
    )

In [28]:
cashflow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187 entries, 0 to 1186
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  1187 non-null   object
 1   company_id          1187 non-null   object
 2   year                1187 non-null   object
 3   operating_activity  1185 non-null   float64
 4   investing_activity  1185 non-null   float64
 5   financing_activity  1185 non-null   float64
 6   net_cash_flow       1185 non-null   float64
dtypes: float64(4), object(3)
memory usage: 65.0+ KB

In [29]:
profitandloss['year'].unique()

array(['Dec 2012', 'Mar 2014', 'Mar 2015', 'Mar 2016', 'Mar 2017',
       'Mar 2018', 'Mar 2019', 'Mar 2020', 'Mar 2021', 'Mar 2022',
       'Mar 2023', 'Mar 2024', 'TTM', 'Mar 2013', 'Dec 2013', 'Dec 2014',
       'Dec 2015', 'Dec 2016', 'Dec 2017', 'Dec 2018', 'Dec 2019',
       'Dec 2020', 'Dec 2021', 'Mar 2023 15', 'Jun 2013', 'Jun 2014',
       'Jun 2015', 'Mar 2016 9m', 'Mar 2011', 'Mar 2012', 'Dec 2022',
       'Dec 2023', 'Sep 2011', 'Sep 2014', 'Sep 2015', 'Sep 2016',
       'Sep 2017', 'Sep 2018', 'Sep 2019', 'Sep 2020', 'Sep 2021',
       'Sep 2022', 'Sep 2023', 'Sep 2024'], dtype=object)

In [30]:
profitandloss['fiscal_year'] = profitandloss['year'].str.extract(r'(\d{4})')

profitandloss['fiscal_year'] = pd.to_numeric(
    profitandloss['fiscal_year'],
    errors='coerce'
)

In [31]:
profitandloss['year'].unique()

array(['Dec 2012', 'Mar 2014', 'Mar 2015', 'Mar 2016', 'Mar 2017',
       'Mar 2018', 'Mar 2019', 'Mar 2020', 'Mar 2021', 'Mar 2022',
       'Mar 2023', 'Mar 2024', 'TTM', 'Mar 2013', 'Dec 2013', 'Dec 2014',
       'Dec 2015', 'Dec 2016', 'Dec 2017', 'Dec 2018', 'Dec 2019',
       'Dec 2020', 'Dec 2021', 'Mar 2023 15', 'Jun 2013', 'Jun 2014',
       'Jun 2015', 'Mar 2016 9m', 'Mar 2011', 'Mar 2012', 'Dec 2022',
       'Dec 2023', 'Sep 2011', 'Sep 2014', 'Sep 2015', 'Sep 2016',
       'Sep 2017', 'Sep 2018', 'Sep 2019', 'Sep 2020', 'Sep 2021',
       'Sep 2022', 'Sep 2023', 'Sep 2024'], dtype=object)

In [32]:
balancesheet['fiscal_year'] = balancesheet['year'].str.extract(r'(\d{4})')

balancesheet['fiscal_year'] = pd.to_numeric(
    balancesheet['fiscal_year'],
    errors='coerce'
)

In [33]:
balancesheet['year'].unique()

array(['Dec 2012', 'Mar 2014', 'Mar 2015', 'Mar 2016', 'Mar 2017',
       'Mar 2018', 'Mar 2019', 'Mar 2020', 'Mar 2021', 'Mar 2022',
       'Mar 2023', 'Mar 2024', 'Sep 2024', 'Mar 2013', 'Dec 2013',
       'Dec 2014', 'Dec 2015', 'Dec 2016', 'Dec 2017', 'Dec 2018',
       'Dec 2019', 'Dec 2020', 'Dec 2021', 'Jun 2013', 'Jun 2014',
       'Jun 2015', 'Dec 2022', 'Dec 2023', 'Mar 2011', 'Mar 2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021',
       '2022', '2023', '2024', '2024.5', 'Sep 2011', 'Sep 2014',
       'Sep 2015', 'Sep 2016', 'Sep 2017', 'Sep 2018', 'Sep 2019',
       'Sep 2020', 'Sep 2021', 'Sep 2022', 'Sep 2023'], dtype=object)

In [34]:
cashflow['fiscal_year'] = cashflow['year'].str.extract(r'(\d{4})')

cashflow['fiscal_year'] = pd.to_numeric(
    cashflow['fiscal_year'],
    errors='coerce'
)

In [35]:
cashflow['year'].unique()

array(['Mar-13', 'Mar-14', 'Mar-15', 'Mar-16', 'Mar-17', 'Mar-18',
       'Mar-19', 'Mar-20', 'Mar-21', 'Mar-22', 'Mar-23', 'Mar-24',
       'Dec 2012', 'Mar 2014', 'Mar 2015', 'Mar 2016', 'Mar 2017',
       'Mar 2018', 'Mar 2019', 'Mar 2020', 'Mar 2021', 'Mar 2022',
       'Mar 2023', 'Mar 2024', 'Mar 2013', 'Dec 2013', 'Dec 2014',
       'Dec 2015', 'Dec 2016', 'Dec 2017', 'Dec 2018', 'Dec 2019',
       'Dec 2020', 'Dec 2021', 'Jun 2013', 'Jun 2014', 'Jun 2015',
       'Dec 2022', 'Dec 2023', 'Sep 2011', 'Sep 2014', 'Sep 2015',
       'Sep 2016', 'Sep 2017', 'Sep 2018', 'Sep 2019', 'Sep 2020',
       'Sep 2021', 'Sep 2022', 'Sep 2023', 'Sep 2024'], dtype=object)

In [36]:
balancesheet['debt_to_equity'] = (
    balancesheet['borrowings'] /
    (
        balancesheet['equity_capital'] +
        balancesheet['reserves']
    )
)

In [37]:
profitandloss['net_profit_margin_pct'] = (
    profitandloss['net_profit'] /
    profitandloss['sales']
) * 100

In [38]:
profitandloss['interest_coverage'] = (
    profitandloss['operating_profit'] /
    profitandloss['interest']
)

In [39]:
cashflow['free_cash_flow'] = (
    cashflow['operating_activity'] +
    cashflow['investing_activity']
)

In [40]:
balancesheet.head()

,id,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_asset,total_assets,fiscal_year,debt_to_equity
0,136,ABB,Dec 2012,21.0,626,0,260,907,109,1,0,798,907,2012,0.0
1,137,ABB,Mar 2014,21.0,767,0,351,1139,98,1,0,1040,1139,2014,0.0
2,138,ABB,Mar 2015,21.0,916,0,436,1374,96,4,0,1274,1374,2015,0.0
3,139,ABB,Mar 2016,21.0,1174,0,421,1616,108,3,0,1505,1616,2016,0.0
4,140,ABB,Mar 2017,21.0,1366,0,679,2066,110,6,0,1950,2066,2017,0.0

In [41]:
profitandloss.head()

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout,fiscal_year,net_profit_margin_pct,interest_coverage
0,61,ABB,Dec 2012,1653,1451,202.0,12.0,33,0,19,215,33.0,145,68.0,25.0,2012.0,8.771930,inf
1,62,ABB,Mar 2014,2276,2009,267.0,12.0,49,0,22,295,33.0,198,93.0,25.0,2014.0,8.699473,inf
2,63,ABB,Mar 2015,2289,1977,312.0,14.0,48,0,15,344,34.0,229,108.0,29.0,2015.0,10.004369,inf
3,64,ABB,Mar 2016,2614,2250,365.0,14.0,50,3,14,398,36.0,255,120.0,29.0,2016.0,9.755164,121.666667
4,65,ABB,Mar 2017,2903,2505,398.0,14.0,57,2,16,436,37.0,277,130.0,31.0,2017.0,9.541853,199.000000

In [42]:
cashflow.head()

,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow,fiscal_year,free_cash_flow
0,37,TCS,Mar-13,11615.0,-6038.0,-5729.0,-152.0,NaN,5577.0
1,38,TCS,Mar-14,14751.0,-9452.0,-5673.0,-374.0,NaN,5299.0
2,39,TCS,Mar-15,19369.0,-1807.0,-17168.0,394.0,NaN,17562.0
3,40,TCS,Mar-16,19109.0,-5010.0,-9666.0,4433.0,NaN,14099.0
4,41,TCS,Mar-17,25223.0,-16895.0,-11026.0,-2698.0,NaN,8328.0

In [43]:
profitandloss.to_csv("clean_profitandloss.csv", index=False)

In [44]:
balancesheet.to_csv("clean_balancesheet.csv", index=False)

In [45]:
companies.to_csv("clean_companies.csv", index=False)

In [46]:
cashflow.to_csv("clean_cashflow.csv", index=False)

In [47]:
analysis.to_csv("clean_analysis.csv", index=False)

In [48]:
prosandcons.to_csv("clean_prosandcons.csv", index=False)

In [49]:
documents.to_csv("clean_documents.csv", index=False)

In [50]:
cashflow['year'].unique()

array(['Mar-13', 'Mar-14', 'Mar-15', 'Mar-16', 'Mar-17', 'Mar-18',
       'Mar-19', 'Mar-20', 'Mar-21', 'Mar-22', 'Mar-23', 'Mar-24',
       'Dec 2012', 'Mar 2014', 'Mar 2015', 'Mar 2016', 'Mar 2017',
       'Mar 2018', 'Mar 2019', 'Mar 2020', 'Mar 2021', 'Mar 2022',
       'Mar 2023', 'Mar 2024', 'Mar 2013', 'Dec 2013', 'Dec 2014',
       'Dec 2015', 'Dec 2016', 'Dec 2017', 'Dec 2018', 'Dec 2019',
       'Dec 2020', 'Dec 2021', 'Jun 2013', 'Jun 2014', 'Jun 2015',
       'Dec 2022', 'Dec 2023', 'Sep 2011', 'Sep 2014', 'Sep 2015',
       'Sep 2016', 'Sep 2017', 'Sep 2018', 'Sep 2019', 'Sep 2020',
       'Sep 2021', 'Sep 2022', 'Sep 2023', 'Sep 2024'], dtype=object)

In [51]:
cashflow['year'] = cashflow['year'].str.replace('-', ' ')

In [52]:
cashflow['year'].unique()

array(['Mar 13', 'Mar 14', 'Mar 15', 'Mar 16', 'Mar 17', 'Mar 18',
       'Mar 19', 'Mar 20', 'Mar 21', 'Mar 22', 'Mar 23', 'Mar 24',
       'Dec 2012', 'Mar 2014', 'Mar 2015', 'Mar 2016', 'Mar 2017',
       'Mar 2018', 'Mar 2019', 'Mar 2020', 'Mar 2021', 'Mar 2022',
       'Mar 2023', 'Mar 2024', 'Mar 2013', 'Dec 2013', 'Dec 2014',
       'Dec 2015', 'Dec 2016', 'Dec 2017', 'Dec 2018', 'Dec 2019',
       'Dec 2020', 'Dec 2021', 'Jun 2013', 'Jun 2014', 'Jun 2015',
       'Dec 2022', 'Dec 2023', 'Sep 2011', 'Sep 2014', 'Sep 2015',
       'Sep 2016', 'Sep 2017', 'Sep 2018', 'Sep 2019', 'Sep 2020',
       'Sep 2021', 'Sep 2022', 'Sep 2023', 'Sep 2024'], dtype=object)

In [53]:
cashflow['fiscal_year'] = cashflow['year'].str.extract(r'(\d{2,4})')

In [54]:
cashflow['fiscal_year'] = cashflow['fiscal_year'].astype(int)

In [55]:
cashflow['fiscal_year'] = cashflow['fiscal_year'].apply(
    lambda x: 2000 + x if x < 100 else x
)

In [56]:
cashflow['year'].unique()

array(['Mar 13', 'Mar 14', 'Mar 15', 'Mar 16', 'Mar 17', 'Mar 18',
       'Mar 19', 'Mar 20', 'Mar 21', 'Mar 22', 'Mar 23', 'Mar 24',
       'Dec 2012', 'Mar 2014', 'Mar 2015', 'Mar 2016', 'Mar 2017',
       'Mar 2018', 'Mar 2019', 'Mar 2020', 'Mar 2021', 'Mar 2022',
       'Mar 2023', 'Mar 2024', 'Mar 2013', 'Dec 2013', 'Dec 2014',
       'Dec 2015', 'Dec 2016', 'Dec 2017', 'Dec 2018', 'Dec 2019',
       'Dec 2020', 'Dec 2021', 'Jun 2013', 'Jun 2014', 'Jun 2015',
       'Dec 2022', 'Dec 2023', 'Sep 2011', 'Sep 2014', 'Sep 2015',
       'Sep 2016', 'Sep 2017', 'Sep 2018', 'Sep 2019', 'Sep 2020',
       'Sep 2021', 'Sep 2022', 'Sep 2023', 'Sep 2024'], dtype=object)

In [57]:
cashflow[['year', 'fiscal_year']].head(10)

0    year  fiscal_year
0  Mar 13         2013
1  Mar 14         2014
2  Mar 15         2015
3  Mar 16         2016
4  Mar 17         2017
5  Mar 18         2018
6  Mar 19         2019
7  Mar 20         2020
8  Mar 21         2021
9  Mar 22         2022

In [58]:
cashflow.to_csv("clean_cashflow.csv", index=False)

In [59]:
ttm_data = profitandloss[profitandloss['year'] == 'TTM']

profitandloss = profitandloss[profitandloss['year'] != 'TTM']

In [60]:
profitandloss['year'].unique()

array(['Dec 2012', 'Mar 2014', 'Mar 2015', 'Mar 2016', 'Mar 2017',
       'Mar 2018', 'Mar 2019', 'Mar 2020', 'Mar 2021', 'Mar 2022',
       'Mar 2023', 'Mar 2024', 'Mar 2013', 'Dec 2013', 'Dec 2014',
       'Dec 2015', 'Dec 2016', 'Dec 2017', 'Dec 2018', 'Dec 2019',
       'Dec 2020', 'Dec 2021', 'Mar 2023 15', 'Jun 2013', 'Jun 2014',
       'Jun 2015', 'Mar 2016 9m', 'Mar 2011', 'Mar 2012', 'Dec 2022',
       'Dec 2023', 'Sep 2011', 'Sep 2014', 'Sep 2015', 'Sep 2016',
       'Sep 2017', 'Sep 2018', 'Sep 2019', 'Sep 2020', 'Sep 2021',
       'Sep 2022', 'Sep 2023', 'Sep 2024'], dtype=object)

In [61]:
profitandloss.to_csv("clean_profitandloss.csv", index=False)

In [62]:
import numpy as np

profitandloss.replace([np.inf, -np.inf], np.nan, inplace=True)

/tmp/ipykernel_520/463284889.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  profitandloss.replace([np.inf, -np.inf], np.nan, inplace=True)

In [63]:
from google.colab import files

files.download("clean_profitandloss.csv")

In [64]:
files.download("clean_balancesheet.csv")

In [65]:
files.download("clean_cashflow.csv")

In [66]:
files.download("clean_companies.csv")

In [67]:
files.download("clean_analysis.csv")
files.download("clean_documents.csv")
files.download("clean_prosandcons.csv")